### ISSUE TITLE
subprocess.CalledProcessError: Command '['git', 'config', 'user.name']' returned non-zero exit status 1

### ISSUE THREAD

**Issue by richardgmcmahon** [dhroth/count_quasars#2]
I am now  running from my desktop and get this error:

subprocess.CalledProcessError: Command '['git', 'config', 'user.name']' returned non-zero exit status 1

full traceback is at end 

Google takes me to:

On Linus I get:
git config --global -l
core.editor=emacs

git config -l
core.editor=emacs

On my mac I get a long list including
user.name=richardgmcmahon

I added by hand (lsst-sims) rgm@calx154(~){1036}> more .gitconfig
[core]
        editor = emacs
[user]
        name=richardgmcmahon

It woks OK now.

(lsst-sims) rgm@calx154(/data/vault/rgm/github/count_quasars){1001}> time python countQuasars.py
Traceback (most recent call last):
  File "countQuasars.py", line 168, in <module>
    producer = subprocess.check_output(["git", "config", "user.name"]).strip()
  File "/data/vault/rgm/anaconda2/envs/lsst-sims/lib/python2.7/subprocess.py", line 219, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['git', 'config', 'user.name']' returned non-zero exit status 1

**Comment by dhroth** [comment]
Ah, yes I assume that git has been setup with your username. You can do that by editing .gitconfig as you did or with git config --global user.name "Sir Daniel I"

I should probably throw an error with directions on how to set your username if it's not set

**Comment by dhroth** [comment]
Okay, I've pushed a change so that it shows an informative error message if you haven't set up git
