### ISSUE TITLE
problem with reading VISTA passes since PhysicalParameters sets maxwavelen value

### ISSUE THREAD

**Issue by richardgmcmahon** [dhroth/count_quasars#5]
It looks like the VISTA throughputs for J, H, K bandpasses are not being 

see https://github.com/lsst/sims_photUtils/blob/master/python/lsst/sims/photUtils/PhysicalParameters.py

self._maxwavelen = 1150.0

changing getMags.getVistaThroughput

from:

vistaBand.readThroughput(throughputsFile)

to

vistaBand.readThroughput(throughputsFile,
                             wavelen_min=500.0,
                             wavelen_max=2500.0,
                             wavelen_step=0.5)

fixes the problem:

plot of correctly read in VISTA filtera and start of WISE W1 filter

![figure_1](https://user-images.githubusercontent.com/2388403/36076467-76614ab8-0f54-11e8-8bb7-7e2db2e2ad50.png)

![bandpasses_2](https://user-images.githubusercontent.com/2388403/36076442-12a69a00-0f54-11e8-9265-6de0203856aa.png)

![figure_1](https://user-images.githubusercontent.com/2388403/36076534-421a5c76-0f55-11e8-8b7e-86be5e20ea71.png)

**Comment by dhroth** [comment]
good catch. I merged the PR
